'use client';

/**
 * Ionicons-compatible icon component.
 *
 * The RN app referenced icons by Ionicons name strings; this maps those exact
 * names onto react-icons' Ionicons 5 set so call sites port over unchanged.
 */
import {
    IoAdd, IoAddCircleOutline, IoAlertCircle, IoArrowBack, IoArrowForward,
    IoBanOutline, IoBarChartOutline, IoBicycleOutline, IoBulbOutline,
    IoCalendarOutline, IoCall, IoCallOutline, IoCamera, IoCarOutline,
    IoCardOutline, IoCart, IoCartOutline, IoCashOutline, IoChatbubbleOutline,
    IoChatbubblesOutline, IoCheckbox, IoCheckmark, IoCheckmarkCircle,
    IoCheckmarkCircleOutline, IoChevronBack, IoChevronForward, IoClose,
    IoCloseCircle, IoCloseCircleOutline, IoEyeOffOutline, IoEyeOutline,
    IoFastFoodOutline, IoFlameOutline, IoFolderOpenOutline, IoGiftOutline,
    IoHeadsetOutline, IoHeart, IoHeartOutline, IoHelpCircleOutline,
    IoHelpOutline, IoHome, IoHomeOutline, IoImageOutline, IoImagesOutline,
    IoInformationCircleOutline, IoList, IoLocation, IoLocationOutline,
    IoLockClosedOutline, IoLogOutOutline, IoLogoFacebook, IoLogoInstagram,
    IoMailOutline, IoMapOutline, IoMegaphoneOutline, IoPaperPlane, IoPause,
    IoPencil, IoPencilOutline, IoPeopleCircleOutline, IoPeopleOutline,
    IoPerson, IoPersonOutline, IoPhonePortraitOutline, IoPizza,
    IoPricetagOutline, IoPrintOutline, IoRadioButtonOn, IoReceiptOutline,
    IoRefreshOutline,
    IoRemove, IoRestaurant, IoRestaurantOutline, IoSearch, IoSearchOutline,
    IoSendOutline, IoShareSocialOutline, IoShieldCheckmark, IoSquareOutline,
    IoStar, IoStarOutline, IoStorefrontOutline, IoTextOutline, IoTicketOutline,
    IoTimeOutline, IoTrash, IoTrashOutline, IoWifiOutline,
} from 'react-icons/io5';

const ICONS = {
    'add': IoAdd,
    'add-circle-outline': IoAddCircleOutline,
    'alert-circle': IoAlertCircle,
    'arrow-back': IoArrowBack,
    'arrow-forward': IoArrowForward,
    'ban-outline': IoBanOutline,
    'bar-chart-outline': IoBarChartOutline,
    'bicycle-outline': IoBicycleOutline,
    'bulb-outline': IoBulbOutline,
    'calendar-outline': IoCalendarOutline,
    'call': IoCall,
    'call-outline': IoCallOutline,
    'camera': IoCamera,
    'car-outline': IoCarOutline,
    'card-outline': IoCardOutline,
    'cart': IoCart,
    'cart-outline': IoCartOutline,
    'cash-outline': IoCashOutline,
    'chatbubble-outline': IoChatbubbleOutline,
    'chatbubbles-outline': IoChatbubblesOutline,
    'checkbox': IoCheckbox,
    'checkmark': IoCheckmark,
    'checkmark-circle': IoCheckmarkCircle,
    'checkmark-circle-outline': IoCheckmarkCircleOutline,
    'chevron-back': IoChevronBack,
    'chevron-forward': IoChevronForward,
    'close': IoClose,
    'close-circle': IoCloseCircle,
    'close-circle-outline': IoCloseCircleOutline,
    'eye-off-outline': IoEyeOffOutline,
    'eye-outline': IoEyeOutline,
    'fast-food-outline': IoFastFoodOutline,
    'flame-outline': IoFlameOutline,
    'folder-open-outline': IoFolderOpenOutline,
    'gift-outline': IoGiftOutline,
    'headset-outline': IoHeadsetOutline,
    'heart': IoHeart,
    'heart-outline': IoHeartOutline,
    'help-circle-outline': IoHelpCircleOutline,
    'help-outline': IoHelpOutline,
    'home': IoHome,
    'home-outline': IoHomeOutline,
    'image-outline': IoImageOutline,
    'images-outline': IoImagesOutline,
    'information-circle-outline': IoInformationCircleOutline,
    'list': IoList,
    'location': IoLocation,
    'location-outline': IoLocationOutline,
    'lock-closed-outline': IoLockClosedOutline,
    'log-out-outline': IoLogOutOutline,
    'logo-facebook': IoLogoFacebook,
    'logo-instagram': IoLogoInstagram,
    'mail-outline': IoMailOutline,
    'map-outline': IoMapOutline,
    'megaphone-outline': IoMegaphoneOutline,
    'paper-plane': IoPaperPlane,
    'pause': IoPause,
    'pencil': IoPencil,
    'pencil-outline': IoPencilOutline,
    'people-circle-outline': IoPeopleCircleOutline,
    'people-outline': IoPeopleOutline,
    'person': IoPerson,
    'person-outline': IoPersonOutline,
    'phone-portrait-outline': IoPhonePortraitOutline,
    'pizza': IoPizza,
    'pricetag-outline': IoPricetagOutline,
    'print-outline': IoPrintOutline,
    'radio-button-on': IoRadioButtonOn,
    'receipt-outline': IoReceiptOutline,
    'refresh-outline': IoRefreshOutline,
    'remove': IoRemove,
    'restaurant': IoRestaurant,
    'restaurant-outline': IoRestaurantOutline,
    'search': IoSearch,
    'search-outline': IoSearchOutline,
    'send-outline': IoSendOutline,
    'share-social-outline': IoShareSocialOutline,
    'shield-checkmark': IoShieldCheckmark,
    'square-outline': IoSquareOutline,
    'star': IoStar,
    'star-outline': IoStarOutline,
    'storefront-outline': IoStorefrontOutline,
    'text-outline': IoTextOutline,
    'ticket-outline': IoTicketOutline,
    'time-outline': IoTimeOutline,
    'trash': IoTrash,
    'trash-outline': IoTrashOutline,
    'wifi-outline': IoWifiOutline,
};

export default function Icon({ name, size = 20, color, className, style }) {
    const Glyph = ICONS[name] || IoHelpOutline;
    return (
        <Glyph
            size={size}
            className={className}
            style={{ color, flexShrink: 0, ...style }}
            aria-hidden="true"
        />
    );
}
